/*
 * This source file was generated by the Gradle 'init' task
 */
package com.group3;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        GymTracking classUnderTest = new GymTracking();
        assertNotNull(classUnderTest);
    }
}
